In [1]:
#import the necessary libraries
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
print(train.info())
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pcl

In [4]:
#let's drop the cabin column as it contains about 70% null values
train.drop(columns=['Cabin'], inplace=True)
test.drop(columns=['Cabin'], inplace=True)

#let's check for null values in other columns
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [5]:
train['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [6]:
train['Embarked'].fillna('S', inplace=True)
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
dtype: int64

In [7]:
test['Fare'].fillna(test['Fare'].mean(), inplace=True)
test.isnull().sum()

PassengerId     0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Ticket          0
Fare            0
Embarked        0
dtype: int64

In [8]:
train_age = np.random.randint(train['Age'].mean() - train['Age'].std(), train['Age'].mean() + train['Age'].std(), 177)
train_age

array([18, 23, 38, 28, 16, 27, 16, 30, 38, 38, 41, 22, 27, 31, 22, 19, 36,
       25, 20, 30, 34, 18, 21, 42, 25, 40, 29, 29, 28, 39, 33, 30, 37, 41,
       35, 32, 15, 25, 40, 19, 28, 30, 36, 32, 36, 37, 16, 19, 42, 18, 40,
       26, 43, 39, 34, 26, 19, 25, 24, 43, 18, 18, 28, 25, 29, 29, 34, 35,
       23, 42, 19, 42, 19, 21, 37, 36, 37, 25, 22, 22, 43, 39, 40, 38, 21,
       41, 26, 30, 23, 15, 27, 42, 32, 35, 37, 29, 31, 29, 22, 41, 41, 30,
       26, 39, 31, 25, 41, 24, 37, 27, 15, 15, 20, 41, 24, 19, 26, 27, 17,
       15, 27, 26, 33, 15, 37, 38, 23, 36, 35, 38, 18, 37, 25, 41, 43, 17,
       35, 31, 25, 23, 41, 16, 22, 19, 40, 36, 39, 32, 32, 24, 19, 34, 18,
       35, 43, 17, 34, 23, 19, 19, 36, 29, 20, 35, 18, 22, 43, 43, 31, 43,
       41, 39, 36, 41, 28, 20, 31])

In [9]:
test_age = np.random.randint(test['Age'].mean() - test['Age'].std(), test['Age'].mean() + test['Age'].std(), 86)
test_age

array([39, 43, 36, 23, 31, 28, 42, 43, 23, 19, 30, 36, 29, 21, 32, 42, 16,
       28, 35, 36, 19, 23, 20, 32, 16, 26, 20, 32, 16, 17, 22, 17, 33, 19,
       27, 41, 30, 31, 24, 41, 18, 24, 18, 19, 16, 39, 23, 18, 39, 43, 43,
       37, 28, 26, 39, 26, 18, 27, 33, 21, 27, 25, 21, 22, 41, 42, 36, 26,
       23, 20, 36, 17, 38, 25, 19, 27, 20, 41, 39, 31, 28, 22, 37, 21, 41,
       18])

In [10]:
train['Age'][train['Age'].isnull()] = train_age

/var/folders/g1/fg3ktwfj5knggpbrg3cb393m0000gn/T/ipykernel_42482/1833702416.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['Age'][train['Age'].isnull()] = train_age


In [11]:
test['Age'][test['Age'].isnull()] = test_age

/var/folders/g1/fg3ktwfj5knggpbrg3cb393m0000gn/T/ipykernel_42482/4013316382.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['Age'][test['Age'].isnull()] = test_age


In [12]:
print(train.isnull().sum())
train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64


PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [13]:
def calculate(n):
    if n==1: return "Alone"
    elif n>1 and n<5: return "Medium"
    else: return "Large"

train['family'] = train['SibSp'] + train['Parch'] + 1
train['fam_size'] = train['family'].apply(calculate)
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  family fam_size  
0      0         A/5 21171   7.2500        S       2   Medium  
1      0          PC 17599  71.2833        C       2   Medium  
2      0  STON/O2. 3101282   7.9250        S       1    Alone  
3      0            113803  53.1000        S       2   Medium  
4      0            373450   8.0500        S       1    Alone

In [14]:
test['family'] = test['SibSp'] + test['Parch'] + 1
test['fam_size'] = test['family'].apply(calculate)

In [15]:
train = train.drop(columns=['SibSp', 'Parch', 'family', 'Name', 'Fare', 'PassengerId', 'Ticket'], axis=1)
train.head()

Survived  Pclass     Sex   Age Embarked fam_size
0         0       3    male  22.0        S   Medium
1         1       1  female  38.0        C   Medium
2         1       3  female  26.0        S    Alone
3         1       1  female  35.0        S   Medium
4         0       3    male  35.0        S    Alone

In [16]:
test = test.drop(columns=['SibSp', 'Parch', 'family', 'Name', 'Fare', 'Ticket'], axis=1)
test.head()

PassengerId  Pclass     Sex   Age Embarked fam_size
0          892       3    male  34.5        Q    Alone
1          893       3  female  47.0        S   Medium
2          894       2    male  62.0        Q    Alone
3          895       3    male  27.0        S    Alone
4          896       3  female  22.0        S   Medium

In [18]:
train = pd.get_dummies(train, columns=['Pclass', 'Sex', 'Embarked', 'fam_size'], drop_first=True)
test = pd.get_dummies(test, columns=['Pclass', 'Sex', 'Embarked', 'fam_size'], drop_first=True)
train.head()

Survived   Age  Pclass_2  Pclass_3  Sex_male  Embarked_Q  Embarked_S  \
0         0  22.0         0         1         1           0           1   
1         1  38.0         0         0         0           0           0   
2         1  26.0         0         1         0           0           1   
3         1  35.0         0         0         0           0           1   
4         0  35.0         0         1         1           0           1   

   fam_size_Large  fam_size_Medium  
0               0                1  
1               0                1  
2               0                0  
3               0                1  
4               0                0

In [19]:
X = train.iloc[:,1:]
Y = train.iloc[:,0]
X

Age  Pclass_2  Pclass_3  Sex_male  Embarked_Q  Embarked_S  \
0    22.0         0         1         1           0           1   
1    38.0         0         0         0           0           0   
2    26.0         0         1         0           0           1   
3    35.0         0         0         0           0           1   
4    35.0         0         1         1           0           1   
..    ...       ...       ...       ...         ...         ...   
886  27.0         1         0         1           0           1   
887  19.0         0         0         0           0           1   
888  31.0         0         1         0           0           1   
889  26.0         0         0         1           0           0   
890  32.0         0         1         1           1           0   

     fam_size_Large  fam_size_Medium  
0                 0                1  
1                 0                1  
2                 0                0  
3                 0                1  
4                 0                0  
..              ...              ...  
886               0                0  
887               0                0  
888               0                1  
889               0                0  
890               0                0  

[891 rows x 8 columns]

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=15)
X_train

Age  Pclass_2  Pclass_3  Sex_male  Embarked_Q  Embarked_S  \
530   2.0         1         0         0           0           1   
124  54.0         0         0         1           0           1   
56   21.0         1         0         0           0           1   
424  18.0         0         1         1           0           1   
664  20.0         0         1         1           0           1   
..    ...       ...       ...       ...         ...         ...   
384  37.0         0         1         1           0           1   
887  19.0         0         0         0           0           1   
645  48.0         0         0         1           0           0   
757  18.0         1         0         1           0           1   
456  65.0         0         0         1           0           1   

     fam_size_Large  fam_size_Medium  
530               0                1  
124               0                1  
56                0                0  
424               0                1  
664               0                1  
..              ...              ...  
384               0                0  
887               0                0  
645               0                1  
757               0                0  
456               0                0  

[712 rows x 8 columns]

In [21]:
from sklearn.tree import DecisionTreeClassifier
DTC = DecisionTreeClassifier()
DTC.fit(X_train,Y_train)

DecisionTreeClassifier()

In [22]:
Y_DTC = DTC.predict(X_test)

In [23]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier()
RFC.fit(X_train,Y_train)

RandomForestClassifier()

In [24]:
Y_RFC = RFC.predict(X_test)

In [25]:
from sklearn.naive_bayes import GaussianNB
GNB = GaussianNB()
GNB.fit(X_train,Y_train)

GaussianNB()

In [26]:
Y_GNB = GNB.predict(X_test)

In [28]:
from sklearn.svm import SVC
SV = SVC()
SV.fit(X_train,Y_train)

SVC()

In [29]:
Y_SVC = SV.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Decision Tree Classifier :")
print("Accuracy", accuracy_score(Y_test,Y_DTC))
print("    Classification report:")
print(classification_report(Y_test,Y_DTC))
print("    Confusion matrix")
print(confusion_matrix(Y_test,Y_DTC))

Decision Tree Classifier :
Accuracy 0.8268156424581006
    Classification report:
              precision    recall  f1-score   support

           0       0.83      0.88      0.85       103
           1       0.83      0.75      0.79        76

    accuracy                           0.83       179
   macro avg       0.83      0.82      0.82       179
weighted avg       0.83      0.83      0.83       179

    Confusion matrix
[[91 12]
 [19 57]]


In [31]:
print("Random Forest Classifier :")
print("Accuracy", accuracy_score(Y_test,Y_RFC))
print("    Classification report:")
print(classification_report(Y_test,Y_RFC))
print("    Confusion matrix")
print(confusion_matrix(Y_test,Y_RFC))

Random Forest Classifier :
Accuracy 0.8100558659217877
    Classification report:
              precision    recall  f1-score   support

           0       0.82      0.85      0.84       103
           1       0.79      0.75      0.77        76

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179

    Confusion matrix
[[88 15]
 [19 57]]


In [32]:
print("Naive Bayes Classifier :")
print("Accuracy", accuracy_score(Y_test,Y_GNB))
print("    Classification report:")
print(classification_report(Y_test,Y_GNB))
print("    Confusion matrix")
print(confusion_matrix(Y_test,Y_GNB))

Naive Bayes Classifier :
Accuracy 0.776536312849162
    Classification report:
              precision    recall  f1-score   support

           0       0.84      0.76      0.80       103
           1       0.71      0.80      0.75        76

    accuracy                           0.78       179
   macro avg       0.77      0.78      0.77       179
weighted avg       0.78      0.78      0.78       179

    Confusion matrix
[[78 25]
 [15 61]]


In [33]:
print("Support Vector Classifier :")
print("Accuracy", accuracy_score(Y_test,Y_SVC))
print("    Classification report:")
print(classification_report(Y_test,Y_SVC))
print("    Confusion matrix")
print(confusion_matrix(Y_test,Y_SVC))

Support Vector Classifier :
Accuracy 0.6089385474860335
    Classification report:
              precision    recall  f1-score   support

           0       0.60      0.95      0.74       103
           1       0.69      0.14      0.24        76

    accuracy                           0.61       179
   macro avg       0.64      0.55      0.49       179
weighted avg       0.64      0.61      0.53       179

    Confusion matrix
[[98  5]
 [65 11]]


In [34]:
pid = test['PassengerId']
pid

0       892
1       893
2       894
3       895
4       896
       ... 
413    1305
414    1306
415    1307
416    1308
417    1309
Name: PassengerId, Length: 418, dtype: int64

In [35]:
test = test.drop(columns=['PassengerId'], axis=1)
test

Age  Pclass_2  Pclass_3  Sex_male  Embarked_Q  Embarked_S  \
0    34.5         0         1         1           1           0   
1    47.0         0         1         0           0           1   
2    62.0         1         0         1           1           0   
3    27.0         0         1         1           0           1   
4    22.0         0         1         0           0           1   
..    ...       ...       ...       ...         ...         ...   
413  21.0         0         1         1           0           1   
414  39.0         0         0         0           0           0   
415  38.5         0         1         1           0           1   
416  41.0         0         1         1           0           1   
417  18.0         0         1         1           0           0   

     fam_size_Large  fam_size_Medium  
0                 0                0  
1                 0                1  
2                 0                0  
3                 0                0  
4                 0                1  
..              ...              ...  
413               0                0  
414               0                0  
415               0                0  
416               0                0  
417               0                1  

[418 rows x 8 columns]

In [36]:
Y_fd = DTC.predict(test)
Y_fr = RFC.predict(test)

In [37]:
decision = pd.DataFrame()
decision['PassengerId'] = pid
decision['Survived'] = Y_fd
decision

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [38]:
random = pd.DataFrame()
random['PassengerId'] = pid
random['Survived'] = Y_fd
random

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [39]:
d2 = DecisionTreeClassifier()
d2.fit(X,Y)

DecisionTreeClassifier()

In [40]:
final = d2.predict(test)

In [41]:
decision2 = pd.DataFrame()
decision2['PassengerId'] = pid
decision2['Survived'] = final
decision2

PassengerId  Survived
0            892         0
1            893         0
2            894         1
3            895         1
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [42]:
#decision.to_csv('decision.csv', index=False)
#decision2.to_csv('decision2.csv', index=False)
#random.to_csv('random.csv', index=False)